---
title: "Example R Markdown"
auhtor: "Haley Lightbody"
date: "2022-09-07"
output: html_document
---
# Main Header
## Sub-header
```{r}
# Install any packages you don't already have.
#install.packages("dplyr")
#install.packages("knitr")
#install.packages("ggplot2")

# Load in the packages you will need.
library(dplyr)
library(knitr)
library(ggplot2)
```
$A = \pi \times r^{2}$
[Class Github](https://github.com/eholdridge2/BIO332)
## Code Chunks
```{r}
norm <- rnorm(100, mean = 0, sd = 1)
```
```{r}
norm <- rnorm(100, mean = 0, sd = 1)
```
```{r, echo = FALSE}
A <- c("a", "a", "b", "b")
B <- c(5, 10, 15, 20)
dataframe <- data.frame(A, B)
print(dataframe)
```
```{r, 'include = false'}
A <- c("a", "a", "b", "b")
B <- c(5, 10, 15, 20)
dataframe <- data.frame(A, B)
print(dataframe)
```
```{r}
dataframe
```

```{r, warning = FALSE}
library(dplyr)
````{r, fig.width = 4, fig.height = 3}
A <- c("a", "a", "b", "b")
B <- c(5, 10, 15, 20)
dataframe <- data.frame(A, B)
print(dataframe)
boxplot(B~A,data=dataframe)
`````
```{r, fig.width = 4, fig.height = 3}
A <- c("a", "a", "b", "b")
B <- c(5, 10, 15, 20)
dataframe <- data.frame(A, B)
print(dataframe)
boxplot(B~A,data=dataframe)
```
```{r}
library(knitr)
kable(dataframe, digits = 2)
```
| Plant | Temp. | Growth |
|:------|:-----:|-------:|
| A     | 20    | 0.65   |
| B     | 20    | 0.95   |
| C     | 20    | 0.15   |
